/**
 * Check ticket Api
 * При авторизации добавть `Bearer` перед токеном
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AuthResult } from '../model/authResult';
import { LoginWithTgDto } from '../model/loginWithTgDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuthService {

    protected basePath = 'http://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Authorize user with locale developer
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authWithLocalDevGet(observe?: 'body', reportProgress?: boolean): Observable<AuthResult>;
    public authWithLocalDevGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthResult>>;
    public authWithLocalDevGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthResult>>;
    public authWithLocalDevGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<AuthResult>(`${this.basePath}/auth/with-local-dev`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Authorize user with Telegram login widget
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authWithTgGet(observe?: 'body', reportProgress?: boolean): Observable<AuthResult>;
    public authWithTgGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthResult>>;
    public authWithTgGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthResult>>;
    public authWithTgGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<AuthResult>(`${this.basePath}/auth/with-tg`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Authorize user with Telegram login widget
     * 
     * @param LoginWithTgDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public authWithTgPost(LoginWithTgDto: LoginWithTgDto, observe?: 'body', reportProgress?: boolean): Observable<AuthResult>;
    public authWithTgPost(LoginWithTgDto: LoginWithTgDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AuthResult>>;
    public authWithTgPost(LoginWithTgDto: LoginWithTgDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AuthResult>>;
    public authWithTgPost(LoginWithTgDto: LoginWithTgDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (LoginWithTgDto === null || LoginWithTgDto === undefined) {
            throw new Error('Required parameter LoginWithTgDto was null or undefined when calling authWithTgPost.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<AuthResult>(`${this.basePath}/auth/with-tg`,
            LoginWithTgDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
