/**
 * Check ticket Api
 * При авторизации добавть `Bearer` перед токеном
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateCheckDto } from '../model/createCheckDto';
import { UpdateActiveDto } from '../model/updateActiveDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ChecksService {

    protected basePath = 'http://localhost/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create new check
     * 
     * @param CreateCheckDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createCheck(CreateCheckDto: CreateCheckDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public createCheck(CreateCheckDto: CreateCheckDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public createCheck(CreateCheckDto: CreateCheckDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public createCheck(CreateCheckDto: CreateCheckDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (CreateCheckDto === null || CreateCheckDto === undefined) {
            throw new Error('Required parameter CreateCheckDto was null or undefined when calling createCheck.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/checks`,
            CreateCheckDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete check by id
     * 
     * @param checkId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCheck(checkId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteCheck(checkId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteCheck(checkId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteCheck(checkId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (checkId === null || checkId === undefined) {
            throw new Error('Required parameter checkId was null or undefined when calling deleteCheck.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.delete<any>(`${this.basePath}/checks/${encodeURIComponent(String(checkId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get check by Id
     * 
     * @param checkId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCheckById(checkId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getCheckById(checkId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getCheckById(checkId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getCheckById(checkId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (checkId === null || checkId === undefined) {
            throw new Error('Required parameter checkId was null or undefined when calling getCheckById.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/checks/${encodeURIComponent(String(checkId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get checks list
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getChecks(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getChecks(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getChecks(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getChecks(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/checks`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update active check by Id
     * 
     * @param UpdateActiveDto 
     * @param checkId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateActive(UpdateActiveDto: UpdateActiveDto, checkId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateActive(UpdateActiveDto: UpdateActiveDto, checkId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateActive(UpdateActiveDto: UpdateActiveDto, checkId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateActive(UpdateActiveDto: UpdateActiveDto, checkId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (UpdateActiveDto === null || UpdateActiveDto === undefined) {
            throw new Error('Required parameter UpdateActiveDto was null or undefined when calling updateActive.');
        }
        if (checkId === null || checkId === undefined) {
            throw new Error('Required parameter checkId was null or undefined when calling updateActive.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<any>(`${this.basePath}/checks/${encodeURIComponent(String(checkId))}/active`,
            UpdateActiveDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update check by Id
     * 
     * @param CreateCheckDto 
     * @param checkId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCheck(CreateCheckDto: CreateCheckDto, checkId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updateCheck(CreateCheckDto: CreateCheckDto, checkId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updateCheck(CreateCheckDto: CreateCheckDto, checkId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updateCheck(CreateCheckDto: CreateCheckDto, checkId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (CreateCheckDto === null || CreateCheckDto === undefined) {
            throw new Error('Required parameter CreateCheckDto was null or undefined when calling updateCheck.');
        }
        if (checkId === null || checkId === undefined) {
            throw new Error('Required parameter checkId was null or undefined when calling updateCheck.');
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.patch<any>(`${this.basePath}/checks/${encodeURIComponent(String(checkId))}`,
            CreateCheckDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
