/**
 * Check ticket Api
 * При авторизации добавть `Bearer` перед токеном
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CityDto } from './cityDto';
import { TypeCarriageDto } from './typeCarriageDto';
import { TypePlaceDto } from './typePlaceDto';


export interface CreateCheckDto { 
    from: CityDto;
    to: CityDto;
    dateTrainGo: string;
    timeFrom: string;
    timeTo: string;
    placeCount: number;
    intervalSearch: number;
    trainCarriage: TypeCarriageDto;
    placeInCarriage: TypePlaceDto;
}
