/**
 * Check ticket Api
 * При авторизации добавть `Bearer` перед токеном
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TypePlaceDto { 
    notShowTopPlace: boolean;
    notShowBottomPlace: boolean;
    notShowLateralPlace: boolean;
    notShowNeatToiletPlace: boolean;
}
