/**
 * Check ticket Api
 * При авторизации добавть `Bearer` перед токеном
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TypeCarriageDto { 
    lux: boolean;
    compartment: boolean;
    berth: boolean;
    seatingFirstClass: boolean;
    seatingSecondClass: boolean;
}
